---
title: "Swimming in it"
author: "Janice Banser"
site: bookdown::bookdown_site
documentclass: book
classoption: openany
---

# Tanzania, retirement, and a conquered mountain

A few things happened in 2005, my mother retired, I finished up a Masters program, and a small group of mostly related Canadian women went to Tanzania. My mom has become a world travellor in the second half of her life -- she climbed Machu Picchu, slept on a hammock on a beach in Belize, spent time backpacking through Scandinavia, and many, many more adventures.  Sadly, I was not able to join her on those trips, but finally, I could join in on her retirement celebration trip, to climb Mt. Kilimanjaro! 

I kept a journal while in East Africa and moved my experiences to a blog when I got home.  We spent almost two months in Tanzania -- we climbed Mt. Kilimanjaro, went on safari, spent time on the Spice Island of Zanzibar, and swam in the Indian Ocean. It really was the trip of a lifetime.  Dip in and see for yourself. 
